services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: ecommerce_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: ecommerce_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  postgres:
    image: postgres:15
    container_name: ecommerce_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spark:
    image: apache/spark:3.5.1
    container_name: ecommerce_spark
    env_file:
      - .env
    environment:
      AWS_DEFAULT_REGION: ap-south-1
      PATH: /opt/spark/bin:${PATH}
    depends_on:
      - kafka
    volumes:
      - ../services/spark:/app
    working_dir: /app
    ports:
      - "4040:4040"
    command:
      - /opt/spark/bin/spark-submit
      - --master
      - local[*]
      - --conf
      - spark.jars.ivy=/tmp/.ivy2
      - --conf
      - spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
      - --conf
      - spark.hadoop.fs.s3a.aws.credentials.provider=com.amazonaws.auth.EnvironmentVariableCredentialsProvider
      - --packages
      - org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262
      - streaming_job.py

  spark_processed:
    image: apache/spark:3.5.1
    container_name: ecommerce_spark_processed
    env_file:
     - .env
    environment:
      AWS_DEFAULT_REGION: ap-south-1
      PATH: /opt/spark/bin:${PATH}
    depends_on:
      - kafka
    volumes:
      - ../services/spark:/app
    working_dir: /app
    ports:
      - "4041:4040"
    command:
      - /opt/spark/bin/spark-submit
      - --master
      - local[*]
      - --conf
      - spark.jars.ivy=/tmp/.ivy2
      - --conf
      - spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
      - --conf
      - spark.hadoop.fs.s3a.aws.credentials.provider=com.amazonaws.auth.EnvironmentVariableCredentialsProvider
      - --packages
      - org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262
      - raw_to_processed.py


  fastapi:
    build:
      context: ../services/api
      dockerfile: Dockerfile
    container_name: ecommerce_fastapi
    depends_on:
      - kafka
      - postgres
      - spark
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ecommerce
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

volumes:
  postgres_data:
  kafka_data:
  zookeeper_data:
  zookeeper_log:
